name: CI/CD on Github Actions Node + Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (if you have any)
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No tests found, skipping"
          fi

      # 5. Prepare lowercase image name and SHA tag
      - name: Prepare lowercase name
        run: |
          echo "IMAGE_NAME=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 6. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build Docker image (with two tags: SHA and latest)
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -t ghcr.io/${{ env.IMAGE_NAME }}:latest .

      # 8. Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
